version: "2.1"
services:
  nextcloud:
    image: lscr.io/linuxserver/nextcloud:latest
    container_name: nextcloud
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ${DISK}/apps/nextcloud:/config
      - ${DISK}:/data
    ports:
      - 6660:443
    restart: unless-stopped