version: "2.1"
services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent
    container_name: qbittorrent
    volumes:
      - /apps/qbittorrent/downloads:/downloads # pathOnMySystem : pathOnDockerContainer
      - /apps/qbittorrent/configuration:/config
    ports:
      - 6881:6881       #tcp connection 
      - 6881:6881/udp   #udp connection
      - 8080:8080       #webUI
  jackett:
    image: lscr.io/linuxserver/jackett
    container_name: jackett
    volumes:
      - /apps/jackett/configuration:/config
      - /apps/qbittorrent/downloads:/downloads
    ports:
      - 9117:9117       #webUI
  
  sonarr:
    image: lscr.io/linuxserver/sonarr
    container_name: sonarr
    volumes:
      - /apps/sonarr/configuration:/config
      - /apps/qbittorrent/downloads:/downloads
      - /media/tv:/tv
    ports:
      - 8989:8989

  radarr:
    image: lscr.io/linuxserver/radarr
    container_name: radarr
    volumes:
      - /apps/radarr/configuration:/config
      - /apps/qbittorrent/downloads:/downloads
      - /media/movies:/movies
    ports:
      - 7878:7878