version: "2"
services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent
    container_name: qbittorrent
    volumes:
      - /disk1/apps/qbittorrent/downloads:/downloads # pathOnMySystem : pathOnDockerContainer
      - /apps/qbittorrent/configuration:/config
    ports:
      - 6881:6881       #tcp connection 
      - 6881:6881/udp   #udp connection
      - 8080:8080       #webUI
  jackett:
    image: lscr.io/linuxserver/jackett
    container_name: jackett
    volumes:
      - /apps/jackett/configuration:/config
      - /disk1/apps/qbittorrent/downloads:/downloads
    ports:
      - 9117:9117       #webUI
  sonarr:
    image: lscr.io/linuxserver/sonarr
    container_name: sonarr
    volumes:
      - /apps/sonarr/configuration:/config
      - /disk1/apps/qbittorrent/downloads:/downloads
      - /disk1/media/tv:/tv #remember to chmod -R -v 777 /tv
    ports:
      - 8989:8989       #webUI
  radarr:
    image: lscr.io/linuxserver/radarr
    container_name: radarr
    volumes:
      - /apps/radarr/configuration:/config
      - /disk1/apps/qbittorrent/downloads:/downloads
      - /disk1/media/movies:/movies #remember to chmod -R -v 777 /movies
    ports:
      - 7878:7878       #webUI
  plex:
    image: lscr.io/linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
     - PLEX_CLAIM=claim-fcUqmxE32r9eiwk74QeM
    volumes: 
      - /apps/plex/configuration:/config
      - /disk1/media/movies:/movies
      - /disk1/media/tvseries:/tv
    ports:
      - 32400:32400

  heimdall:
    image: lscr.io/linuxserver/heimdall
    container_name: heimdall
    volumes:
      - /apps/heimdal/configuration:/config
    ports:
      - 80:80
      - 443:433
