#must add ${DISK} variable in portainer environment
version: "2"
services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    volumes:
      - ${DISK}/apps/vaultwarden/data:/data/
    ports:
      - 8181:8