#must add $DISK variable in portainer environment
version: "3.8"
networks:
  homeserver:
    driver: bridge
services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent
    container_name: qbittorrent
    volumes:
      - $DISK/apps/qbittorrent/downloads:/downloads # pathOnMySystem : pathOnDockerContainer
      - $DISK/apps/qbittorrent/configuration:/config
    ports:
      - 6881:6881       #tcp connection 
      - 6881:6881/udp   #udp connection
      - 8080:8080       #webUI
    networks:
      - homeserver
    restart: unless-stopped
  jackett:
    image: lscr.io/linuxserver/jackett
    container_name: jackett
    volumes:
      - $DISK/apps/jackett/configuration:/config
      - $DISK/apps/qbittorrent/downloads:/downloads
    ports:
      - 9117:9117       #webUI
    networks:
      - homeserver
    restart: unless-stopped
  sonarr:
    image: lscr.io/linuxserver/sonarr
    container_name: sonarr
    volumes:
      - $DISK/apps/sonarr/configuration:/config
      - $DISK/apps/qbittorrent/downloads:/downloads
      - $DISK/media/tv:/tv #remember to chmod -R -v 777 /tv
    ports:
      - 8989:8989       #webUI
    networks:
      - homeserver
    restart: unless-stopped
  radarr:
    image: lscr.io/linuxserver/radarr
    container_name: radarr
    volumes:
      - $DISK/apps/radarr/configuration:/config
      - $DISK/apps/qbittorrent/downloads:/downloads
      - $DISK/media/movies:/movies #remember to chmod -R -v 777 /movies
    ports:
      - 7878:7878       #webUI
    networks:
      - homeserver
    restart: unless-stopped
  plex:
    image: lscr.io/linuxserver/plex
    container_name: plex
    environment:
     - PLEX_CLAIM=claim-fcUqmxE32r9eiwk74QeM
    volumes: 
      - $DISK/apps/plex/configuration:/config
      - $DISK/media/movies:/movies
      - $DISK/media/tvseries:/tv
    ports:
      - 32400:32400
    networks:
      - homeserver
    restart: unless-stopped
  heimdall:
    image: lscr.io/linuxserver/heimdall
    container_name: heimdall
    volumes:
      - $DISK/apps/heimdal/configuration:/config
    ports:
      - 8050:80
      - 8051:433
    networks:
      - homeserver
    restart: unless-stopped
