version: "3.8"
services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent
    container_name: qBittorrent
    volumes:
      - $DISK/.apps/qbittorrent:/config
      - $DISK/downloads:/downloads
    ports:
      - 8080:8080
      - 6881:6811
      - 6881:6811/udp
    restart: unless-stopped
  jackett:
    image: lscr.io/linuxserver/jackett
    container_name: jackett
    volumes:
      - $DISK/.apps/jackett/configuration:/config
      - $DISK/downloads:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped