version: "3.8"
services:
  uptime_kuma:
    container_name: kuma
    image: louislam/uptime-kuma
    restart: unless-stopped
    volumes:
      - $CONFIG/kuma:/app/data
    ports:
      - 3001:3001
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
    environment:
      TZ: 'America/Chicago'
      WEBPASSWORD: 'familia1'
    volumes:
      - './etc-pihole:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'
    restart: unless-stopped